# Generated by Django 2.1.2 on 2018-11-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicicleta',
            name='imagen_bicicleta',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_bicicletas'),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='imagen_equipamiento',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_equipamiento'),
        ),
    ]
