# Generated by Django 2.1.2 on 2018-11-17 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_auto_20181117_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='arriendo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participantes', models.PositiveIntegerField()),
                ('duracion', models.PositiveIntegerField()),
                ('a_bicicleta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.bicicleta')),
                ('a_equipamiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.equipamiento')),
            ],
        ),
    ]
