# Generated by Django 2.1.3 on 2018-11-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_empleado',
            field=models.BooleanField(default=False),
        ),
    ]
