# Generated by Django 2.1.3 on 2018-11-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_auto_20181116_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
